### PR TITLE
Add support for QRs without a termination byte

### PR DESCRIPTION
**Pull request by cozmo**
#77 reports an issue scanning a QR code without the termination byte. Feels safe to return the data we have assuming we've completely exhausted the data stream, even if we don't encounter the termination bit. This matches the behavior of ZXIng. 

Also added the image as a test case.

### CODE REVIEW

**Comment by cozmo** [comment]
Hmm, reading [this](https://www.thonky.com/qr-code-tutorial/data-encoding#add-a-terminator-of-0s-if-necessary) makes it seem like we've misunderstood under what circumstance a termination byte would show up, and also how (aka it could just be 1 0?) 

Need to investigate a bit more.

**Comment by cozmo** [comment]
Updated in 93d2eb9 to follow the spec which says

> The end of data in the symbol is signalled by the Terminator sequence of 0 bits, as defined in Table 2, appended to the data bit stream following the final mode segment. The Terminator shall be omitted if the data bit stream completely fills the capacity of the symbol, or abbreviated if the remaining capacity of the symbol is less than 4 bits.

**Comment by nathanhoel** [comment]
@cozmo This fix does not appear in the 1.2 package that was pushed to NPM February 2019 - would you be able to have this added to NPM?
This specific issue is causing a large number of our QR codes to fail because the string we use happens to be really close to the exact capacity of the stream.

**Comment by nathanhoel** [comment]
I actually see the problem - the /dist folder is out of date, it has not been updated for 2 years missing many of the changes since then.

**Pull request merged**
