### PR TITLE
Better handling some null cases

### PR DESCRIPTION
**Pull request by josefdlange**
Ran into a couple cases where I was getting a spew of errors, and I wanted to shut them up appropriately... hope this looks good to you. I'm not a strong TypeScript guy but it seemed straightforward enough. Even wrote some tests around it....

### CODE REVIEW

**Comment by josefdlange** [comment]
Somebody? Anybody?

**Comment by cozmo** [comment]
Hey @josefdlange so sorry about the delay - It appears I wasn't "watching" my own repo, and missed this PR. 

These changes seem straight forward enough to me, I'm going to say LGTM and merge - should deploy it to npm later today.

**Comment by josefdlange** [comment]
No worries 🎉 🍻

**Comment by cozmo** [comment]
@josefdlange Published this as version `0.2.1` just now. Thanks again for the fixes and would love to hear about any ways you're using this library.

**Pull request merged**
