### PR TITLE
Fixes build process to cleanup before creating new files

### LINKED ISSUE #48: the build generates bitmatrix.d.ts in lowercase
This will throw an error in all files importing "BitMatrix" as the file can not be found on an OS which cares about this.

I expected bitmatrix.d.ts to be BitMatrix.d.ts

### PR DESCRIPTION
**Pull request by lordnox**
This fixes #48 
It will remove the `./dist` directory and update the build process to clean up before creating new files.

### CODE REVIEW

**Comment by cozmo** [comment]
@lordnox currently it appears this PR removes _all_ files from the `dist` directory. Can you run `make build` and then re-push? In general the concept of clearing out the `dist` directory makes sense, so thanks for the change.

**Comment by cozmo** [comment]
Just saw your comment on the first commit re: avoiding merge conflicts. Will merge this and rebuild then.

**Comment by Ruffio** [comment]
Will this PR be merged?

**Comment by cozmo** [comment]
@Ruffio this PR was merged on Feb 28.

**Comment by Ruffio** [comment]
Lol I see :-)

**Pull request merged**
